# Generated by Django 3.1.5 on 2021-09-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quote', models.CharField(max_length=10)),
                ('stock_display_name', models.CharField(max_length=20)),
            ],
        ),
    ]
